/**
 * PHASE-CLAIM-FAMILY-ALGORITHM-MATRIX-V3-OFFICIAL-AMAZON-COVERAGE
 * Read-only claim family discovery — official SP-API + Seller Central + normalized tables.
 * Extends V1/V2 with full Amazon reimbursement/fee coverage audit. No DB writes.
 */

import { AMAZON_REPORT_REGISTRY, type AmazonSyncKind } from "../../pipeline/amazon-report-registry";
import {
  AMAZON_REPORT_CROSSWALK_LIVE,
  AMAZON_REPORT_CROSSWALK_PLACEHOLDERS,
  SP_API_REPORT_TYPE_TO_SYNC_KIND,
} from "../../amazon/amazon-report-type-crosswalk";
import { FEE_ADJUSTED_REIMBURSEMENT_FORMULA } from "../../fees/amazon-fee-adjusted-reimbursement-estimate-model-v1";
import { CLAIM_ALGORITHM_HARD_RULES } from "./claim-family-algorithm-matrix-v1";

export type V3FamilyClassification =
  | "claim_family"
  | "claim_family_when_source_available"
  | "review_signal_only"
  | "lifecycle_only"
  | "lifecycle_grouping_only";

export type V3SourceAvailability =
  | "live_table"
  | "live_importer"
  | "live_generator"
  | "partial"
  | "planned_sp_api"
  | "unsupported_file"
  | "empty_connector"
  | "lifecycle_derived"
  | "finances_api_archive";

export type ClaimFamilyMatrixV3Entry = {
  family_key: string;
  display_name: string;
  classification: V3FamilyClassification;
  v1_reviewed: boolean;
  v2_status: "unchanged" | "renamed" | "split" | "added_v2" | "added_v3" | "deprecated_grouping";
  required_reports_api: string[];
  normalized_tables: string[];
  registry_sync_kinds: AmazonSyncKind[];
  required_identifiers: string[];
  quantity_formula: string;
  fee_amount_formula: string;
  estimated_amazon_payout_formula: string;
  observed_reimbursement_formula: string;
  internal_cost_loss_formula: string;
  product_linkage_requirement:
    | "required_before_trusted_money"
    | "required_before_product_story"
    | "recommended"
    | "identifier_only"
    | "not_applicable";
  trid_edges_required: string[];
  source_confidence: { high: string; medium: string; low: string };
  current_availability: V3SourceAvailability;
  blocked_reason: string | null;
  implementation_priority: "P0" | "P1" | "P2" | "P3" | "deferred";
};

export const V2_FAMILY_COUNT = 34;
export const V3_ADDED_COUNT = 7;
export const V3_CLAIM_FAMILY_COUNT = 41;

export const REMOVED_OR_MERGED_FAMILIES = {
  split: {
    removal_shipment_missing_damaged: ["removal_shipment_missing", "removal_damaged_during_removal"],
  },
  renamed: {
    reimbursement_missing: "missing_reimbursement",
    reimbursement_partial_incorrect: "partial_incorrect_reimbursement",
  },
  merged_into_existing: {
    product_dimensions_weight_tier_mismatch: "dimension_weight_fee_issue",
    stranded_inventory_listing_issue: "stranded_inventory_signal",
  },
  deprecated_grouping_only: {
    stranded_expired_review_signal:
      "lifecycle dashboard grouping — use stranded_inventory_signal + expired_inventory_action_signal for signals",
  },
} as const;

export const ADDED_FAMILIES_V3 = [
  "fba_overage_aged_inventory_fee_issue",
  "recommended_removal_aged_inventory_action",
  "storage_utilization_cubic_volume_issue",
  "customer_shipment_sales_refund_mismatch",
  "finances_api_event_mismatch",
  "removal_fee_refund_mismatch",
  "long_term_storage_aged_surcharge_issue",
] as const;

const PAYOUT = FEE_ADJUSTED_REIMBURSEMENT_FORMULA.estimated_amazon_payout;
const OBSERVED = FEE_ADJUSTED_REIMBURSEMENT_FORMULA.observed_reimbursement;
const COGS_LOSS = FEE_ADJUSTED_REIMBURSEMENT_FORMULA.internal_cost_loss;
const FEE_GAP = "fee_overcharge_gap = charged_fee - expected_fee";
const REIMB_GAP = "reimbursement_gap = estimated - observed";
const QTY_COGS = "claim_quantity = GREATEST(0, expected_qty - observed_qty); actual_loss = claim_quantity × unit_cost_basis";

function entry(
  partial: ClaimFamilyMatrixV3Entry,
): ClaimFamilyMatrixV3Entry {
  return partial;
}

/** Official SP-API / Seller Central → normalized table mapping (curated from registry + crosswalk). */
export const OFFICIAL_REPORT_TYPE_MAPPING: Record<
  string,
  { sp_api_type: string | null; seller_central_label: string | null; sync_kind: AmazonSyncKind | null; table: string | null }
> = {
  FBA_RETURNS: {
    sp_api_type: "GET_FBA_FULFILLMENT_CUSTOMER_RETURNS_DATA",
    seller_central_label: "FBA Customer Returns",
    sync_kind: "FBA_RETURNS",
    table: AMAZON_REPORT_REGISTRY.FBA_RETURNS.sync_target_table,
  },
  INVENTORY_LEDGER: {
    sp_api_type: "GET_LEDGER_DETAIL_VIEW_DATA",
    seller_central_label: "Inventory Ledger Detail View",
    sync_kind: "INVENTORY_LEDGER",
    table: AMAZON_REPORT_REGISTRY.INVENTORY_LEDGER.sync_target_table,
  },
  REIMBURSEMENTS: {
    sp_api_type: "GET_FBA_REIMBURSEMENTS_DATA",
    seller_central_label: "FBA Reimbursements",
    sync_kind: "REIMBURSEMENTS",
    table: AMAZON_REPORT_REGISTRY.REIMBURSEMENTS.sync_target_table,
  },
  SETTLEMENT: {
    sp_api_type: "GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2",
    seller_central_label: "Settlement Flat File V2",
    sync_kind: "SETTLEMENT",
    table: AMAZON_REPORT_REGISTRY.SETTLEMENT.sync_target_table,
  },
  REMOVAL_ORDER: {
    sp_api_type: "GET_FBA_FULFILLMENT_REMOVAL_ORDER_DETAIL_DATA",
    seller_central_label: "Removal Order Detail",
    sync_kind: "REMOVAL_ORDER",
    table: AMAZON_REPORT_REGISTRY.REMOVAL_ORDER.sync_target_table,
  },
  REMOVAL_SHIPMENT: {
    sp_api_type: "GET_FBA_FULFILLMENT_REMOVAL_SHIPMENT_DETAIL_DATA",
    seller_central_label: "Removal Shipment Detail",
    sync_kind: "REMOVAL_SHIPMENT",
    table: AMAZON_REPORT_REGISTRY.REMOVAL_SHIPMENT.sync_target_table,
  },
  FEE_PREVIEW: {
    sp_api_type: "GET_FBA_ESTIMATED_FBA_FEES_TXT_DATA",
    seller_central_label: "Fee Preview",
    sync_kind: "FEE_PREVIEW",
    table: AMAZON_REPORT_REGISTRY.FEE_PREVIEW.sync_target_table,
  },
  MONTHLY_STORAGE_FEES: {
    sp_api_type: "GET_FBA_STORAGE_FEE_CHARGES_DATA",
    seller_central_label: "Monthly Inventory Storage Fees",
    sync_kind: "MONTHLY_STORAGE_FEES",
    table: AMAZON_REPORT_REGISTRY.MONTHLY_STORAGE_FEES.sync_target_table,
  },
  LONGTERM_STORAGE: {
    sp_api_type: "GET_FBA_FULFILLMENT_LONGTERM_STORAGE_FEE_CHARGES_DATA",
    seller_central_label: "Long Term Storage Fee Charges",
    sync_kind: "MONTHLY_STORAGE_FEES",
    table: AMAZON_REPORT_REGISTRY.MONTHLY_STORAGE_FEES.sync_target_table,
  },
  INBOUND_PERFORMANCE: {
    sp_api_type: "GET_FBA_INBOUND_PERFORMANCE_DATA",
    seller_central_label: "Inbound Performance",
    sync_kind: "INBOUND_PERFORMANCE",
    table: AMAZON_REPORT_REGISTRY.INBOUND_PERFORMANCE.sync_target_table,
  },
  REPLACEMENTS: {
    sp_api_type: null,
    seller_central_label: "Replacements",
    sync_kind: "REPLACEMENTS",
    table: AMAZON_REPORT_REGISTRY.REPLACEMENTS.sync_target_table,
  },
  FBA_GRADE_AND_RESELL: {
    sp_api_type: null,
    seller_central_label: "FBA Grade and Resell",
    sync_kind: "FBA_GRADE_AND_RESELL",
    table: AMAZON_REPORT_REGISTRY.FBA_GRADE_AND_RESELL.sync_target_table,
  },
  MANAGE_FBA_INVENTORY: {
    sp_api_type: "GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA",
    seller_central_label: "Manage FBA Inventory",
    sync_kind: "MANAGE_FBA_INVENTORY",
    table: AMAZON_REPORT_REGISTRY.MANAGE_FBA_INVENTORY.sync_target_table,
  },
  RESERVED_INVENTORY: {
    sp_api_type: null,
    seller_central_label: "Reserved Inventory",
    sync_kind: "RESERVED_INVENTORY",
    table: AMAZON_REPORT_REGISTRY.RESERVED_INVENTORY.sync_target_table,
  },
  STRANDED: {
    sp_api_type: "GET_STRANDED_INVENTORY_UI_DATA",
    seller_central_label: "Stranded Inventory",
    sync_kind: null,
    table: "amazon_stranded_inventory (planned)",
  },
  LOW_INVENTORY_FEE: {
    sp_api_type: null,
    seller_central_label: "Low-Inventory-Level Fee Report",
    sync_kind: null,
    table: "planned: amazon_low_inventory_fees",
  },
  RETURNS_PROCESSING_FEE: {
    sp_api_type: null,
    seller_central_label: "Returns Processing Fee",
    sync_kind: null,
    table: "planned: amazon_returns_processing_fees",
  },
  INBOUND_PLACEMENT_FEE: {
    sp_api_type: null,
    seller_central_label: "Inbound Placement Service Fees",
    sync_kind: null,
    table: "planned: amazon_inbound_placement_fees",
  },
  INVENTORY_AGED: {
    sp_api_type: "GET_FBA_INVENTORY_AGED_DATA",
    seller_central_label: "Inventory Health / Aged Inventory",
    sync_kind: null,
    table: "lifecycle_derived from ledger + manage_fba",
  },
  RESTOCK_RECOMMENDATIONS: {
    sp_api_type: "GET_RESTOCK_INVENTORY_RECOMMENDATIONS_REPORT",
    seller_central_label: "Restock Recommendations",
    sync_kind: null,
    table: "lifecycle_derived",
  },
  ALL_ORDERS: {
    sp_api_type: "GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL",
    seller_central_label: "All Orders / Fulfilled Shipments",
    sync_kind: "ALL_ORDERS",
    table: AMAZON_REPORT_REGISTRY.ALL_ORDERS.sync_target_table,
  },
  SAFET: {
    sp_api_type: null,
    seller_central_label: "SAFE-T Claims",
    sync_kind: "SAFET_CLAIMS",
    table: AMAZON_REPORT_REGISTRY.SAFET_CLAIMS.sync_target_table,
  },
  FINANCES_API: {
    sp_api_type: "Finances API listFinancialEvents",
    seller_central_label: null,
    sync_kind: null,
    table: "amazon_finances_events",
  },
  PRODUCT_FEES_API: {
    sp_api_type: "Product Fees API getMyFeesEstimate*",
    seller_central_label: "Revenue Calculator (benchmark only)",
    sync_kind: null,
    table: "fee_estimate_snapshots (planned)",
  },
};

export const MISSING_SOURCE_MAPPING = [
  {
    report_label: "Low-Inventory-Level Fee Report",
    sp_api_type: "unknown — file-first",
    registry_gap: "not in AMAZON_REPORT_REGISTRY",
    sample_zip: "unsupported UNKNOWN importer",
    families_blocked: ["low_inventory_fee_issue"],
  },
  {
    report_label: "Returns Processing Fee",
    sp_api_type: "unknown — file-first",
    registry_gap: "not in AMAZON_REPORT_REGISTRY",
    sample_zip: "unsupported UNKNOWN importer",
    families_blocked: ["returns_processing_fee_issue"],
  },
  {
    report_label: "Inbound Placement Service Fees",
    sp_api_type: "unknown — file-first",
    registry_gap: "not in AMAZON_REPORT_REGISTRY",
    sample_zip: "unsupported UNKNOWN importer",
    families_blocked: ["inbound_placement_fee_issue"],
  },
  {
    report_label: "Stranded Inventory",
    sp_api_type: "GET_STRANDED_INVENTORY_UI_DATA",
    registry_gap: "no AmazonSyncKind; amazon_stranded_inventory table not migrated",
    sample_zip: "expected later",
    families_blocked: ["stranded_inventory_signal"],
  },
  {
    report_label: "GET_LEDGER_DETAIL_VIEW_DATA",
    sp_api_type: "GET_LEDGER_DETAIL_VIEW_DATA",
    registry_gap: "not in SP_API_REPORT_TYPE_TO_SYNC_KIND crosswalk",
    sample_zip: "Detail View required; reject Daily Summary",
    families_blocked: ["warehouse_lost_inventory", "warehouse_damaged_inventory", "inventory_adjustment_error"],
  },
  {
    report_label: "GET_FBA_ESTIMATED_FBA_FEES_TXT_DATA",
    sp_api_type: "GET_FBA_ESTIMATED_FBA_FEES_TXT_DATA",
    registry_gap: "not in SP_API_REPORT_TYPE_TO_SYNC_KIND; API worker planned",
    families_blocked: ["fba_fee_overcharge", "dimension_weight_fee_issue"],
  },
  {
    report_label: "Product Fees API",
    sp_api_type: "getMyFeesEstimateForASIN/SKU/batch",
    registry_gap: "not implemented in repo",
    families_blocked: ["all fee-adjusted payout estimates"],
  },
  {
    report_label: "product_cost_snapshots",
    sp_api_type: null,
    registry_gap: "table not migrated; SellerSnap importer missing",
    families_blocked: ["internal_cost_loss lane for all inventory families"],
  },
  {
    report_label: "Finances API archive",
    sp_api_type: "listFinancialEvents",
    registry_gap: "amazon_finances_events exists; reconciler not built",
    families_blocked: ["finances_api_event_mismatch"],
  },
] as const;

/** Complete V3 claim family matrix — 41 families. */
export const CLAIM_FAMILY_MATRIX_V3: readonly ClaimFamilyMatrixV3Entry[] = [
  // ── V1 returns / scanner (reviewed) ─────────────────────────────────────
  entry({
    family_key: "physical_return_scanner_issue",
    display_name: "Physical return scanner issue",
    classification: "claim_family",
    v1_reviewed: true,
    v2_status: "unchanged",
    required_reports_api: ["scanner capture", "GET_FBA_FULFILLMENT_CUSTOMER_RETURNS_DATA (anti-match)"],
    normalized_tables: ["return_items", "packages", "amazon_returns"],
    registry_sync_kinds: ["FBA_RETURNS"],
    required_identifiers: ["fnsku", "lpn", "tracking_number"],
    quantity_formula: "claim_quantity = scanned_units not on manifest",
    fee_amount_formula: COGS_LOSS,
    estimated_amazon_payout_formula: PAYOUT,
    observed_reimbursement_formula: OBSERVED,
    internal_cost_loss_formula: COGS_LOSS,
    product_linkage_requirement: "required_before_trusted_money",
    trid_edges_required: ["return_item", "product_link", "scanner_capture"],
    source_confidence: { high: "scan + return match", medium: "scan only", low: "no linkage" },
    current_availability: "live_generator",
    blocked_reason: null,
    implementation_priority: "P0",
  }),
  entry({
    family_key: "customer_return_not_reimbursed",
    display_name: "Customer return not reimbursed",
    classification: "claim_family",
    v1_reviewed: true,
    v2_status: "unchanged",
    required_reports_api: ["GET_FBA_FULFILLMENT_CUSTOMER_RETURNS_DATA", "GET_LEDGER_DETAIL_VIEW_DATA", "GET_FBA_REIMBURSEMENTS_DATA"],
    normalized_tables: ["amazon_returns", "amazon_inventory_ledger", "amazon_reimbursements"],
    registry_sync_kinds: ["FBA_RETURNS", "INVENTORY_LEDGER", "REIMBURSEMENTS"],
    required_identifiers: ["fnsku", "order_id", "return_id", "lpn"],
    quantity_formula: QTY_COGS,
    fee_amount_formula: REIMB_GAP,
    estimated_amazon_payout_formula: PAYOUT,
    observed_reimbursement_formula: OBSERVED,
    internal_cost_loss_formula: COGS_LOSS,
    product_linkage_requirement: "required_before_trusted_money",
    trid_edges_required: ["return_reference", "product_link", "claim_to_reimbursement"],
    source_confidence: { high: "return + anti-reimbursement + linkage", medium: "return only", low: "no FBA returns API sync" },
    current_availability: "partial",
    blocked_reason: "FBA returns API worker Phase 1B not live",
    implementation_priority: "P0",
  }),
  entry({
    family_key: "refund_without_return",
    display_name: "Refund without return",
    classification: "claim_family",
    v1_reviewed: true,
    v2_status: "unchanged",
    required_reports_api: ["GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2", "GET_LEDGER_DETAIL_VIEW_DATA"],
    normalized_tables: ["amazon_settlements", "amazon_inventory_ledger"],
    registry_sync_kinds: ["SETTLEMENT", "INVENTORY_LEDGER"],
    required_identifiers: ["order_id", "sku", "fnsku"],
    quantity_formula: "claim_quantity = refunded_units without matching return event",
    fee_amount_formula: REIMB_GAP,
    estimated_amazon_payout_formula: PAYOUT,
    observed_reimbursement_formula: "settlement refund lines",
    internal_cost_loss_formula: COGS_LOSS,
    product_linkage_requirement: "required_before_trusted_money",
    trid_edges_required: ["order_reference", "settlement_reference", "product_link"],
    source_confidence: { high: "settlement + ledger anti-return", medium: "settlement only", low: "conflicting sources" },
    current_availability: "partial",
    blocked_reason: "Ledger Detail View ingest gate",
    implementation_priority: "P1",
  }),
  entry({
    family_key: "wrong_item_returned",
    display_name: "Wrong item returned",
    classification: "claim_family",
    v1_reviewed: true,
    v2_status: "unchanged",
    required_reports_api: ["GET_FBA_FULFILLMENT_CUSTOMER_RETURNS_DATA", "scanner/OCR evidence"],
    normalized_tables: ["amazon_returns", "return_items"],
    registry_sync_kinds: ["FBA_RETURNS"],
    required_identifiers: ["lpn", "expected_fnsku", "received_fnsku"],
    quantity_formula: "claim_quantity = wrong_item_units",
    fee_amount_formula: COGS_LOSS,
    estimated_amazon_payout_formula: PAYOUT,
    observed_reimbursement_formula: OBSERVED,
    internal_cost_loss_formula: COGS_LOSS,
    product_linkage_requirement: "required_before_trusted_money",
    trid_edges_required: ["return_item", "product_link", "evidence_image"],
    source_confidence: { high: "scanner mismatch + return", medium: "return disposition", low: "no evidence" },
    current_availability: "live_generator",
    blocked_reason: null,
    implementation_priority: "P1",
  }),
  entry({
    family_key: "empty_box_return",
    display_name: "Empty box return",
    classification: "claim_family",
    v1_reviewed: true,
    v2_status: "unchanged",
    required_reports_api: ["GET_FBA_FULFILLMENT_CUSTOMER_RETURNS_DATA"],
    normalized_tables: ["amazon_returns", "return_items"],
    registry_sync_kinds: ["FBA_RETURNS"],
    required_identifiers: ["lpn", "order_id", "fnsku"],
    quantity_formula: "claim_quantity = empty_box_units",
    fee_amount_formula: COGS_LOSS,
    estimated_amazon_payout_formula: PAYOUT,
    observed_reimbursement_formula: OBSERVED,
    internal_cost_loss_formula: COGS_LOSS,
    product_linkage_requirement: "required_before_trusted_money",
    trid_edges_required: ["return_item", "product_link", "evidence_image"],
    source_confidence: { high: "scan empty + return", medium: "return reason", low: "no scan" },
    current_availability: "live_generator",
    blocked_reason: null,
    implementation_priority: "P1",
  }),
  entry({
    family_key: "customer_damaged_return",
    display_name: "Customer damaged return",
    classification: "review_signal_only",
    v1_reviewed: true,
    v2_status: "unchanged",
    required_reports_api: ["GET_FBA_FULFILLMENT_CUSTOMER_RETURNS_DATA"],
    normalized_tables: ["amazon_returns"],
    registry_sync_kinds: ["FBA_RETURNS"],
    required_identifiers: ["lpn", "disposition", "fnsku"],
    quantity_formula: "claim_quantity = NULL; display damaged_units",
    fee_amount_formula: "NULL at signal",
    estimated_amazon_payout_formula: "NULL",
    observed_reimbursement_formula: OBSERVED,
    internal_cost_loss_formula: "NULL unless policy promotes to claim",
    product_linkage_requirement: "recommended",
    trid_edges_required: ["return_reference", "product_link"],
    source_confidence: { high: "return disposition CUSTOMER_DAMAGED", medium: "return only", low: "no import" },
    current_availability: "partial",
    blocked_reason: "Typically non-reimbursable — review before claim",
    implementation_priority: "P3",
  }),
  // ── Removal / disposal ───────────────────────────────────────────────────
  entry({
    family_key: "removal_order_discrepancy",
    display_name: "Removal order discrepancy",
    classification: "claim_family",
    v1_reviewed: true,
    v2_status: "unchanged",
    required_reports_api: ["GET_FBA_FULFILLMENT_REMOVAL_ORDER_DETAIL_DATA", "GET_FBA_FULFILLMENT_REMOVAL_SHIPMENT_DETAIL_DATA"],
    normalized_tables: ["amazon_removals", "amazon_removal_shipments", "expected_packages"],
    registry_sync_kinds: ["REMOVAL_ORDER", "REMOVAL_SHIPMENT"],
    required_identifiers: ["order_id", "fnsku", "sku", "tracking_number"],
    quantity_formula: "claim_quantity = GREATEST(0, detail_qty - shipment_qty) clean rows only",
    fee_amount_formula: COGS_LOSS,
    estimated_amazon_payout_formula: PAYOUT,
    observed_reimbursement_formula: OBSERVED,
    internal_cost_loss_formula: COGS_LOSS,
    product_linkage_requirement: "required_before_trusted_money",
    trid_edges_required: ["removal_order", "removal_shipment", "product_link"],
    source_confidence: { high: "detail vs shipment + clean EP", medium: "detail only", low: "superseded/disputed" },
    current_availability: "live_generator",
    blocked_reason: null,
    implementation_priority: "P0",
  }),
  entry({
    family_key: "removal_shipment_missing",
    display_name: "Removal shipment missing",
    classification: "claim_family",
    v1_reviewed: true,
    v2_status: "split",
    required_reports_api: ["GET_FBA_FULFILLMENT_REMOVAL_SHIPMENT_DETAIL_DATA"],
    normalized_tables: ["amazon_removal_shipments", "expected_packages"],
    registry_sync_kinds: ["REMOVAL_SHIPMENT"],
    required_identifiers: ["order_id", "tracking_number", "fnsku"],
    quantity_formula: "claim_quantity = shipped_missing_units",
    fee_amount_formula: COGS_LOSS,
    estimated_amazon_payout_formula: PAYOUT,
    observed_reimbursement_formula: OBSERVED,
    internal_cost_loss_formula: COGS_LOSS,
    product_linkage_requirement: "required_before_trusted_money",
    trid_edges_required: ["removal_shipment", "product_link"],
    source_confidence: { high: "shipment expected not received", medium: "partial shipment", low: "disputed EP" },
    current_availability: "live_generator",
    blocked_reason: null,
    implementation_priority: "P1",
  }),
  entry({
    family_key: "removal_damaged_during_removal",
    display_name: "Removal damaged during removal",
    classification: "claim_family",
    v1_reviewed: true,
    v2_status: "split",
    required_reports_api: ["GET_FBA_FULFILLMENT_REMOVAL_SHIPMENT_DETAIL_DATA", "GET_LEDGER_DETAIL_VIEW_DATA"],
    normalized_tables: ["amazon_removal_shipments", "amazon_inventory_ledger"],
    registry_sync_kinds: ["REMOVAL_SHIPMENT", "INVENTORY_LEDGER"],
    required_identifiers: ["order_id", "fnsku", "disposition"],
    quantity_formula: "claim_quantity = damaged_during_removal_units",
    fee_amount_formula: COGS_LOSS,
    estimated_amazon_payout_formula: PAYOUT,
    observed_reimbursement_formula: OBSERVED,
    internal_cost_loss_formula: COGS_LOSS,
    product_linkage_requirement: "required_before_trusted_money",
    trid_edges_required: ["removal_shipment", "ledger_reference", "product_link"],
    source_confidence: { high: "shipment damage + ledger", medium: "shipment only", low: "no ledger detail" },
    current_availability: "partial",
    blocked_reason: "Ledger Detail View gate",
    implementation_priority: "P2",
  }),
  entry({
    family_key: "disposed_without_reimbursement",
    display_name: "Disposed/destroyed without reimbursement",
    classification: "claim_family",
    v1_reviewed: true,
    v2_status: "unchanged",
    required_reports_api: ["GET_LEDGER_DETAIL_VIEW_DATA", "GET_FBA_REIMBURSEMENTS_DATA"],
    normalized_tables: ["amazon_inventory_ledger", "amazon_reimbursements"],
    registry_sync_kinds: ["INVENTORY_LEDGER", "REIMBURSEMENTS"],
    required_identifiers: ["fnsku", "reference_id", "disposition"],
    quantity_formula: QTY_COGS,
    fee_amount_formula: REIMB_GAP,
    estimated_amazon_payout_formula: PAYOUT,
    observed_reimbursement_formula: OBSERVED,
    internal_cost_loss_formula: COGS_LOSS,
    product_linkage_requirement: "required_before_trusted_money",
    trid_edges_required: ["ledger_reference", "claim_to_reimbursement", "product_link"],
    source_confidence: { high: "ledger dispose + anti-reimbursement", medium: "ledger only", low: "summary ledger" },
    current_availability: "partial",
    blocked_reason: "Ledger Detail + reimbursement anti-join",
    implementation_priority: "P1",
  }),
  // ── Warehouse / ledger ───────────────────────────────────────────────────
  entry({
    family_key: "warehouse_lost_inventory",
    display_name: "Warehouse lost inventory",
    classification: "claim_family",
    v1_reviewed: true,
    v2_status: "unchanged",
    required_reports_api: ["GET_LEDGER_DETAIL_VIEW_DATA", "GET_FBA_REIMBURSEMENTS_DATA"],
    normalized_tables: ["amazon_inventory_ledger", "amazon_reimbursements"],
    registry_sync_kinds: ["INVENTORY_LEDGER", "REIMBURSEMENTS"],
    required_identifiers: ["fnsku", "reference_id", "event_type"],
    quantity_formula: QTY_COGS,
    fee_amount_formula: REIMB_GAP,
    estimated_amazon_payout_formula: PAYOUT,
    observed_reimbursement_formula: OBSERVED,
    internal_cost_loss_formula: COGS_LOSS,
    product_linkage_requirement: "required_before_trusted_money",
    trid_edges_required: ["ledger_reference", "claim_to_reimbursement", "product_link"],
    source_confidence: { high: "ledger MISC_ADJUSTMENT lost + anti-reimbursement", medium: "ledger event", low: "Daily Summary only" },
    current_availability: "partial",
    blocked_reason: "Detail View ingest + generator",
    implementation_priority: "P1",
  }),
  entry({
    family_key: "warehouse_damaged_inventory",
    display_name: "Warehouse damaged inventory",
    classification: "claim_family",
    v1_reviewed: true,
    v2_status: "unchanged",
    required_reports_api: ["GET_LEDGER_DETAIL_VIEW_DATA", "GET_FBA_REIMBURSEMENTS_DATA"],
    normalized_tables: ["amazon_inventory_ledger", "amazon_reimbursements"],
    registry_sync_kinds: ["INVENTORY_LEDGER", "REIMBURSEMENTS"],
    required_identifiers: ["fnsku", "reference_id", "disposition"],
    quantity_formula: QTY_COGS,
    fee_amount_formula: REIMB_GAP,
    estimated_amazon_payout_formula: PAYOUT,
    observed_reimbursement_formula: OBSERVED,
    internal_cost_loss_formula: COGS_LOSS,
    product_linkage_requirement: "required_before_trusted_money",
    trid_edges_required: ["ledger_reference", "claim_to_reimbursement", "product_link"],
    source_confidence: { high: "ledger damaged + anti-reimbursement", medium: "ledger only", low: "summary ledger" },
    current_availability: "partial",
    blocked_reason: "Detail View ingest",
    implementation_priority: "P1",
  }),
  entry({
    family_key: "inventory_adjustment_error",
    display_name: "Inventory adjustment error",
    classification: "claim_family",
    v1_reviewed: true,
    v2_status: "unchanged",
    required_reports_api: ["GET_LEDGER_DETAIL_VIEW_DATA", "GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2"],
    normalized_tables: ["amazon_inventory_ledger", "amazon_settlements"],
    registry_sync_kinds: ["INVENTORY_LEDGER", "SETTLEMENT"],
    required_identifiers: ["fnsku", "reference_id", "adjustment_reason"],
    quantity_formula: "claim_quantity = erroneous_adjustment_units",
    fee_amount_formula: REIMB_GAP,
    estimated_amazon_payout_formula: PAYOUT,
    observed_reimbursement_formula: OBSERVED,
    internal_cost_loss_formula: COGS_LOSS,
    product_linkage_requirement: "required_before_trusted_money",
    trid_edges_required: ["ledger_reference", "settlement_reference", "product_link"],
    source_confidence: { high: "ledger + settlement reconcile", medium: "ledger only", low: "virtual bundle incomplete" },
    current_availability: "partial",
    blocked_reason: "INVENTORY_ADJUSTMENT_VIRTUAL bundle not built",
    implementation_priority: "P2",
  }),
  // ── Inbound ──────────────────────────────────────────────────────────────
  entry({
    family_key: "inbound_shipment_shortage",
    display_name: "Inbound shipment shortage",
    classification: "claim_family",
    v1_reviewed: true,
    v2_status: "unchanged",
    required_reports_api: ["GET_FBA_INBOUND_PERFORMANCE_DATA"],
    normalized_tables: ["amazon_inbound_performance"],
    registry_sync_kinds: ["INBOUND_PERFORMANCE"],
    required_identifiers: ["shipment_id", "fnsku", "sku"],
    quantity_formula: "claim_quantity = GREATEST(0, sent - received)",
    fee_amount_formula: COGS_LOSS,
    estimated_amazon_payout_formula: PAYOUT,
    observed_reimbursement_formula: OBSERVED,
    internal_cost_loss_formula: COGS_LOSS,
    product_linkage_requirement: "required_before_trusted_money",
    trid_edges_required: ["inbound_shipment", "product_link"],
    source_confidence: { high: "inbound performance shortage", medium: "partial receipt", low: "no inbound data" },
    current_availability: "live_importer",
    blocked_reason: null,
    implementation_priority: "P2",
  }),
  entry({
    family_key: "inbound_receiving_miscount",
    display_name: "Inbound receiving miscount",
    classification: "claim_family",
    v1_reviewed: true,
    v2_status: "unchanged",
    required_reports_api: ["GET_FBA_INBOUND_PERFORMANCE_DATA", "GET_LEDGER_DETAIL_VIEW_DATA"],
    normalized_tables: ["amazon_inbound_performance", "amazon_inventory_ledger"],
    registry_sync_kinds: ["INBOUND_PERFORMANCE", "INVENTORY_LEDGER"],
    required_identifiers: ["shipment_id", "fnsku"],
    quantity_formula: "claim_quantity = ABS(expected_received - ledger_received)",
    fee_amount_formula: COGS_LOSS,
    estimated_amazon_payout_formula: PAYOUT,
    observed_reimbursement_formula: OBSERVED,
    internal_cost_loss_formula: COGS_LOSS,
    product_linkage_requirement: "required_before_trusted_money",
    trid_edges_required: ["inbound_shipment", "ledger_reference", "product_link"],
    source_confidence: { high: "inbound + ledger agree on error", medium: "inbound only", low: "conflict" },
    current_availability: "partial",
    blocked_reason: "Ledger detail join",
    implementation_priority: "P2",
  }),
  entry({
    family_key: "inbound_placement_fee_issue",
    display_name: "Inbound placement fee issue",
    classification: "claim_family_when_source_available",
    v1_reviewed: false,
    v2_status: "added_v2",
    required_reports_api: ["Inbound Placement Service Fees (file)", "GET_FBA_INBOUND_PERFORMANCE_DATA"],
    normalized_tables: ["amazon_inbound_performance", "amazon_settlements", "planned: amazon_inbound_placement_fees"],
    registry_sync_kinds: ["INBOUND_PERFORMANCE"],
    required_identifiers: ["shipment_id", "fnsku", "placement_option"],
    quantity_formula: "claim_quantity = 1 per fee line",
    fee_amount_formula: FEE_GAP,
    estimated_amazon_payout_formula: "N/A — fee family",
    observed_reimbursement_formula: "settlement placement fee lines",
    internal_cost_loss_formula: "NULL",
    product_linkage_requirement: "required_before_trusted_money",
    trid_edges_required: ["inbound_shipment", "claim_to_settlement", "product_link"],
    source_confidence: { high: "placement report + settlement", medium: "settlement only", low: "no importer" },
    current_availability: "unsupported_file",
    blocked_reason: "Placement fee report UNKNOWN in registry",
    implementation_priority: "P2",
  }),
  // ── Reimbursement / settlement ───────────────────────────────────────────
  entry({
    family_key: "missing_reimbursement",
    display_name: "Missing reimbursement",
    classification: "claim_family",
    v1_reviewed: true,
    v2_status: "renamed",
    required_reports_api: ["GET_FBA_REIMBURSEMENTS_DATA", "GET_LEDGER_DETAIL_VIEW_DATA"],
    normalized_tables: ["amazon_reimbursements", "amazon_inventory_ledger"],
    registry_sync_kinds: ["REIMBURSEMENTS", "INVENTORY_LEDGER"],
    required_identifiers: ["fnsku", "reason_code", "reference_id"],
    quantity_formula: QTY_COGS,
    fee_amount_formula: REIMB_GAP,
    estimated_amazon_payout_formula: PAYOUT,
    observed_reimbursement_formula: OBSERVED,
    internal_cost_loss_formula: COGS_LOSS,
    product_linkage_requirement: "required_before_trusted_money",
    trid_edges_required: ["ledger_reference", "claim_to_reimbursement", "product_link"],
    source_confidence: { high: "ledger loss + zero reimbursement", medium: "ledger event", low: "no COGS" },
    current_availability: "live_generator",
    blocked_reason: null,
    implementation_priority: "P0",
  }),
  entry({
    family_key: "partial_incorrect_reimbursement",
    display_name: "Partial/incorrect reimbursement",
    classification: "claim_family",
    v1_reviewed: true,
    v2_status: "renamed",
    required_reports_api: ["GET_FBA_REIMBURSEMENTS_DATA"],
    normalized_tables: ["amazon_reimbursements"],
    registry_sync_kinds: ["REIMBURSEMENTS"],
    required_identifiers: ["fnsku", "reimbursement_id", "reason_code"],
    quantity_formula: "claim_quantity = under_reimbursed_units",
    fee_amount_formula: REIMB_GAP,
    estimated_amazon_payout_formula: PAYOUT,
    observed_reimbursement_formula: OBSERVED,
    internal_cost_loss_formula: COGS_LOSS,
    product_linkage_requirement: "required_before_trusted_money",
    trid_edges_required: ["claim_to_reimbursement", "product_link"],
    source_confidence: { high: "expected vs observed delta", medium: "partial amount", low: "no benchmark" },
    current_availability: "live_generator",
    blocked_reason: null,
    implementation_priority: "P1",
  }),
  entry({
    family_key: "settlement_refund_anomaly",
    display_name: "Settlement/refund anomaly",
    classification: "claim_family",
    v1_reviewed: true,
    v2_status: "unchanged",
    required_reports_api: ["GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2"],
    normalized_tables: ["amazon_settlements", "financial_reference_resolver"],
    registry_sync_kinds: ["SETTLEMENT"],
    required_identifiers: ["settlement_id", "order_id", "transaction_type"],
    quantity_formula: "claim_quantity = anomalous_transaction_count OR unit delta",
    fee_amount_formula: "refund_delta = expected - settlement_amount",
    estimated_amazon_payout_formula: PAYOUT,
    observed_reimbursement_formula: "settlement_amount",
    internal_cost_loss_formula: COGS_LOSS,
    product_linkage_requirement: "required_before_trusted_money",
    trid_edges_required: ["settlement_reference", "order_reference", "product_link"],
    source_confidence: { high: "settlement + order reconcile", medium: "settlement line", low: "orphan line" },
    current_availability: "live_generator",
    blocked_reason: null,
    implementation_priority: "P1",
  }),
  entry({
    family_key: "safet_followup",
    display_name: "SAFE-T follow-up",
    classification: "claim_family_when_source_available",
    v1_reviewed: true,
    v2_status: "unchanged",
    required_reports_api: ["SAFE-T export"],
    normalized_tables: ["amazon_safet_claims"],
    registry_sync_kinds: ["SAFET_CLAIMS"],
    required_identifiers: ["safet_claim_id", "order_id"],
    quantity_formula: "claim_quantity = open_safet_units",
    fee_amount_formula: REIMB_GAP,
    estimated_amazon_payout_formula: PAYOUT,
    observed_reimbursement_formula: "safet.total_reimbursement_amount",
    internal_cost_loss_formula: COGS_LOSS,
    product_linkage_requirement: "required_before_trusted_money",
    trid_edges_required: ["safet_claim", "order_reference", "product_link"],
    source_confidence: { high: "SAFE-T row + reimbursement", medium: "header only", low: "empty connector" },
    current_availability: "empty_connector",
    blocked_reason: "SAFE-T 0 data rows on staging",
    implementation_priority: "P3",
  }),
  entry({
    family_key: "customer_shipment_sales_refund_mismatch",
    display_name: "Customer shipment sales vs refund/reimbursement mismatch",
    classification: "claim_family",
    v1_reviewed: false,
    v2_status: "added_v3",
    required_reports_api: ["GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL", "GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2", "GET_FBA_REIMBURSEMENTS_DATA"],
    normalized_tables: ["amazon_all_orders", "amazon_settlements", "amazon_reimbursements"],
    registry_sync_kinds: ["ALL_ORDERS", "SETTLEMENT", "REIMBURSEMENTS"],
    required_identifiers: ["order_id", "sku", "fnsku", "shipment_id"],
    quantity_formula: "claim_quantity = shipped_units - reimbursed_units - retained_units",
    fee_amount_formula: "sales_proceeds_gap = order_sale_total - refunds - reimbursements",
    estimated_amazon_payout_formula: PAYOUT,
    observed_reimbursement_formula: OBSERVED,
    internal_cost_loss_formula: COGS_LOSS,
    product_linkage_requirement: "required_before_trusted_money",
    trid_edges_required: ["order_reference", "shipment_reference", "claim_to_settlement", "product_link"],
    source_confidence: { high: "all_orders + settlement + reimbursement reconcile", medium: "orders + settlement", low: "missing order grain" },
    current_availability: "partial",
    blocked_reason: "ALL_ORDERS importer live but cross-order reconciler not built",
    implementation_priority: "P2",
  }),
  entry({
    family_key: "finances_api_event_mismatch",
    display_name: "Finances API event mismatch",
    classification: "review_signal_only",
    v1_reviewed: false,
    v2_status: "added_v3",
    required_reports_api: ["Finances API listFinancialEvents", "GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2"],
    normalized_tables: ["amazon_finances_events", "amazon_settlements", "amazon_finances_event_groups"],
    registry_sync_kinds: ["SETTLEMENT"],
    required_identifiers: ["event_group_id", "financial_event_id", "order_id"],
    quantity_formula: "claim_quantity = NULL; display unmatched_event_count",
    fee_amount_formula: "NULL at signal; display event_amount_delta",
    estimated_amazon_payout_formula: "NULL",
    observed_reimbursement_formula: "finances_event_amount vs settlement_line",
    internal_cost_loss_formula: "NULL",
    product_linkage_requirement: "recommended",
    trid_edges_required: ["finances_event", "settlement_reference"],
    source_confidence: { high: "finances + settlement match", medium: "finances only", low: "archive empty" },
    current_availability: "finances_api_archive",
    blocked_reason: "Reconciler not built; promote to claim after match proof",
    implementation_priority: "P3",
  }),
  // ── Fee families ─────────────────────────────────────────────────────────
  entry({
    family_key: "fba_fee_overcharge",
    display_name: "FBA fee overcharge",
    classification: "claim_family",
    v1_reviewed: true,
    v2_status: "unchanged",
    required_reports_api: ["Product Fees API", "GET_FBA_ESTIMATED_FBA_FEES_TXT_DATA", "GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2"],
    normalized_tables: ["amazon_fee_preview", "amazon_settlements", "product_packaging_dimensions_current"],
    registry_sync_kinds: ["FEE_PREVIEW", "SETTLEMENT"],
    required_identifiers: ["fnsku", "asin", "sku"],
    quantity_formula: "claim_quantity = 1 per SKU fee dispute period",
    fee_amount_formula: FEE_GAP,
    estimated_amazon_payout_formula: PAYOUT,
    observed_reimbursement_formula: "settlement fba_fees",
    internal_cost_loss_formula: "NULL",
    product_linkage_requirement: "required_before_trusted_money",
    trid_edges_required: ["product_link", "fee_preview_reference", "claim_to_settlement"],
    source_confidence: { high: "Product Fees API + settlement", medium: "fee_preview only", low: "no fee source" },
    current_availability: "empty_connector",
    blocked_reason: "fee_preview empty; Product Fees API not wired",
    implementation_priority: "P1",
  }),
  entry({
    family_key: "monthly_storage_fee_overcharge",
    display_name: "Monthly storage fee overcharge",
    classification: "claim_family",
    v1_reviewed: true,
    v2_status: "unchanged",
    required_reports_api: ["GET_FBA_STORAGE_FEE_CHARGES_DATA", "GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2"],
    normalized_tables: ["amazon_monthly_storage_fees", "amazon_settlements", "product_packaging_dimensions_current"],
    registry_sync_kinds: ["MONTHLY_STORAGE_FEES", "SETTLEMENT"],
    required_identifiers: ["fnsku", "storage_month"],
    quantity_formula: "claim_quantity = 1 per (fnsku, storage_month)",
    fee_amount_formula: "storage_overcharge_gap = charged_storage - expected_storage",
    estimated_amazon_payout_formula: "N/A — fee family",
    observed_reimbursement_formula: "settlement storage lines",
    internal_cost_loss_formula: "NULL",
    product_linkage_requirement: "required_before_trusted_money",
    trid_edges_required: ["product_link", "storage_fee_reference", "claim_to_settlement"],
    source_confidence: { high: "storage report + PC04 volume proof", medium: "report only", low: "empty storage table" },
    current_availability: "empty_connector",
    blocked_reason: "monthly_storage_fees empty; API worker import fail in sample pull",
    implementation_priority: "P2",
  }),
  entry({
    family_key: "long_term_storage_aged_surcharge_issue",
    display_name: "Long-term storage / aged inventory surcharge",
    classification: "claim_family_when_source_available",
    v1_reviewed: false,
    v2_status: "added_v3",
    required_reports_api: ["GET_FBA_FULFILLMENT_LONGTERM_STORAGE_FEE_CHARGES_DATA", "GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2"],
    normalized_tables: ["amazon_monthly_storage_fees", "amazon_settlements"],
    registry_sync_kinds: ["MONTHLY_STORAGE_FEES"],
    required_identifiers: ["fnsku", "storage_month", "inventory_age_bucket"],
    quantity_formula: "claim_quantity = 1 per long_term_fee_line",
    fee_amount_formula: "storage_overcharge_gap for aged tier",
    estimated_amazon_payout_formula: "N/A",
    observed_reimbursement_formula: "settlement long-term storage lines",
    internal_cost_loss_formula: "NULL",
    product_linkage_requirement: "required_before_trusted_money",
    trid_edges_required: ["product_link", "storage_fee_reference"],
    source_confidence: { high: "longterm report + settlement", medium: "settlement only", low: "no longterm ingest" },
    current_availability: "planned_sp_api",
    blocked_reason: "Longterm storage maps to MONTHLY_STORAGE_FEES but no age bucket discriminator wired",
    implementation_priority: "P2",
  }),
  entry({
    family_key: "storage_utilization_cubic_volume_issue",
    display_name: "Storage utilization / cubic volume issue",
    classification: "claim_family_when_source_available",
    v1_reviewed: false,
    v2_status: "added_v3",
    required_reports_api: ["GET_FBA_STORAGE_FEE_CHARGES_DATA", "product_packaging_dimensions_current"],
    normalized_tables: ["amazon_monthly_storage_fees", "product_packaging_dimensions_current"],
    registry_sync_kinds: ["MONTHLY_STORAGE_FEES"],
    required_identifiers: ["fnsku", "cubic_feet", "storage_month"],
    quantity_formula: "claim_quantity = 1 per volume dispute",
    fee_amount_formula: "expected_storage = cubic_feet × rate_card; storage_overcharge_gap",
    estimated_amazon_payout_formula: "N/A",
    observed_reimbursement_formula: "charged storage from report",
    internal_cost_loss_formula: "NULL",
    product_linkage_requirement: "required_before_trusted_money",
    trid_edges_required: ["product_link", "packaging_dimensions", "storage_fee_reference"],
    source_confidence: { high: "PC04 dims + storage report", medium: "report only", low: "no dims" },
    current_availability: "partial",
    blocked_reason: "PC04 coverage incomplete; storage table empty",
    implementation_priority: "P2",
  }),
  entry({
    family_key: "dimension_weight_fee_issue",
    display_name: "Dimension/weight fee issue (incl. product tier mismatch)",
    classification: "claim_family",
    v1_reviewed: true,
    v2_status: "unchanged",
    required_reports_api: ["GET_FBA_ESTIMATED_FBA_FEES_TXT_DATA", "Product Fees API", "Catalog Items API dimensions"],
    normalized_tables: ["amazon_fee_preview", "product_packaging_dimensions_current"],
    registry_sync_kinds: ["FEE_PREVIEW"],
    required_identifiers: ["fnsku", "asin", "size_tier"],
    quantity_formula: "claim_quantity = 1 per SKU dimension dispute",
    fee_amount_formula: FEE_GAP,
    estimated_amazon_payout_formula: PAYOUT,
    observed_reimbursement_formula: "settlement fulfillment fee",
    internal_cost_loss_formula: "NULL",
    product_linkage_requirement: "required_before_trusted_money",
    trid_edges_required: ["product_link", "packaging_dimensions", "fee_preview_reference"],
    source_confidence: { high: "PC04 vs Amazon charged tier", medium: "fee_preview tier", low: "no dims" },
    current_availability: "partial",
    blocked_reason: "fee_preview empty; merges product_dimensions_weight_tier_mismatch scope",
    implementation_priority: "P2",
  }),
  entry({
    family_key: "low_inventory_fee_issue",
    display_name: "Low Inventory Level Fee issue",
    classification: "claim_family_when_source_available",
    v1_reviewed: false,
    v2_status: "added_v2",
    required_reports_api: ["Low-Inventory-Level Fee Report", "GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA"],
    normalized_tables: ["amazon_manage_fba_inventory", "amazon_settlements", "planned: amazon_low_inventory_fees"],
    registry_sync_kinds: ["MANAGE_FBA_INVENTORY"],
    required_identifiers: ["fnsku", "sku", "fee_month"],
    quantity_formula: "claim_quantity = 1 per (fnsku, fee_month)",
    fee_amount_formula: FEE_GAP,
    estimated_amazon_payout_formula: "N/A",
    observed_reimbursement_formula: "settlement low-inventory fee lines",
    internal_cost_loss_formula: "NULL",
    product_linkage_requirement: "required_before_trusted_money",
    trid_edges_required: ["product_link", "claim_to_settlement"],
    source_confidence: { high: "fee report + manage_fba threshold", medium: "settlement only", low: "no importer" },
    current_availability: "unsupported_file",
    blocked_reason: "Low-inventory fee UNKNOWN in sample zip audit",
    implementation_priority: "P2",
  }),
  entry({
    family_key: "returns_processing_fee_issue",
    display_name: "Returns Processing Fee overcharge",
    classification: "claim_family_when_source_available",
    v1_reviewed: false,
    v2_status: "added_v2",
    required_reports_api: ["Returns Processing Fee report", "GET_FBA_FULFILLMENT_CUSTOMER_RETURNS_DATA"],
    normalized_tables: ["amazon_returns", "amazon_settlements", "planned: amazon_returns_processing_fees"],
    registry_sync_kinds: ["FBA_RETURNS"],
    required_identifiers: ["fnsku", "return_id", "order_id"],
    quantity_formula: "claim_quantity = 1 per disputed fee line",
    fee_amount_formula: FEE_GAP,
    estimated_amazon_payout_formula: "N/A",
    observed_reimbursement_formula: "settlement returns processing credits",
    internal_cost_loss_formula: "NULL",
    product_linkage_requirement: "required_before_trusted_money",
    trid_edges_required: ["return_reference", "claim_to_settlement", "product_link"],
    source_confidence: { high: "returns fee report + return match", medium: "settlement", low: "unsupported file" },
    current_availability: "unsupported_file",
    blocked_reason: "Returns processing fee UNKNOWN importer",
    implementation_priority: "P2",
  }),
  // ── Replacements / grade-resell ──────────────────────────────────────────
  entry({
    family_key: "replacement_mismatch_without_reimbursement",
    display_name: "Replacement reimbursement mismatch",
    classification: "claim_family_when_source_available",
    v1_reviewed: false,
    v2_status: "added_v2",
    required_reports_api: ["Replacements report", "GET_FBA_REIMBURSEMENTS_DATA"],
    normalized_tables: ["amazon_replacements", "amazon_reimbursements"],
    registry_sync_kinds: ["REPLACEMENTS", "REIMBURSEMENTS"],
    required_identifiers: ["original_order_id", "replacement_order_id", "fnsku"],
    quantity_formula: "GREATEST(0, replacement_qty - reimbursed_qty)",
    fee_amount_formula: REIMB_GAP,
    estimated_amazon_payout_formula: PAYOUT,
    observed_reimbursement_formula: OBSERVED,
    internal_cost_loss_formula: COGS_LOSS,
    product_linkage_requirement: "required_before_trusted_money",
    trid_edges_required: ["order_reference", "claim_to_reimbursement", "product_link"],
    source_confidence: { high: "replacements + anti-reimbursement", medium: "replacements report", low: "no importer run" },
    current_availability: "live_importer",
    blocked_reason: "REPLACEMENTS registry live; generator not built",
    implementation_priority: "P2",
  }),
  entry({
    family_key: "fba_grade_and_resell_anomaly",
    display_name: "FBA Grade & Resell anomaly",
    classification: "claim_family_when_source_available",
    v1_reviewed: false,
    v2_status: "added_v2",
    required_reports_api: ["FBA Grade and Resell report", "GET_FBA_REIMBURSEMENTS_DATA"],
    normalized_tables: ["amazon_fba_grade_and_resell", "amazon_reimbursements", "amazon_settlements"],
    registry_sync_kinds: ["FBA_GRADE_AND_RESELL", "REIMBURSEMENTS"],
    required_identifiers: ["fnsku", "grade_tier", "order_id"],
    quantity_formula: "COALESCE(graded_units, 1)",
    fee_amount_formula: "reimbursement_gap OR fee_overcharge_gap",
    estimated_amazon_payout_formula: PAYOUT,
    observed_reimbursement_formula: OBSERVED,
    internal_cost_loss_formula: COGS_LOSS,
    product_linkage_requirement: "required_before_trusted_money",
    trid_edges_required: ["product_link", "claim_to_reimbursement"],
    source_confidence: { high: "grade report + reimbursement", medium: "report only", low: "empty table" },
    current_availability: "live_importer",
    blocked_reason: "Generator not built; table may be empty",
    implementation_priority: "P3",
  }),
  entry({
    family_key: "removal_fee_refund_mismatch",
    display_name: "Removal fee/refund mismatch",
    classification: "claim_family",
    v1_reviewed: false,
    v2_status: "added_v3",
    required_reports_api: ["GET_FBA_FULFILLMENT_REMOVAL_ORDER_DETAIL_DATA", "GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2"],
    normalized_tables: ["amazon_removals", "amazon_settlements"],
    registry_sync_kinds: ["REMOVAL_ORDER", "SETTLEMENT"],
    required_identifiers: ["order_id", "fnsku", "removal_fee_type"],
    quantity_formula: "claim_quantity = 1 per removal fee dispute",
    fee_amount_formula: "removal_fee_gap = charged_removal_fee - expected_removal_fee",
    estimated_amazon_payout_formula: "N/A",
    observed_reimbursement_formula: "settlement removal fee / refund lines",
    internal_cost_loss_formula: "NULL",
    product_linkage_requirement: "required_before_trusted_money",
    trid_edges_required: ["removal_order", "claim_to_settlement", "product_link"],
    source_confidence: { high: "removal detail + settlement fee", medium: "settlement only", low: "no fee column mapping" },
    current_availability: "partial",
    blocked_reason: "Removal fee column mapping in settlements not standardized",
    implementation_priority: "P2",
  }),
  // ── Inventory signals (review / lifecycle) ─────────────────────────────
  entry({
    family_key: "reserved_inventory_stuck_signal",
    display_name: "Reserved inventory stuck signal",
    classification: "review_signal_only",
    v1_reviewed: false,
    v2_status: "added_v2",
    required_reports_api: ["Reserved Inventory report", "GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA"],
    normalized_tables: ["amazon_reserved_inventory", "amazon_manage_fba_inventory"],
    registry_sync_kinds: ["RESERVED_INVENTORY", "MANAGE_FBA_INVENTORY"],
    required_identifiers: ["fnsku", "asin"],
    quantity_formula: "claim_quantity = NULL; display reserved_qty where age > threshold",
    fee_amount_formula: "NULL",
    estimated_amazon_payout_formula: "NULL",
    observed_reimbursement_formula: "N/A",
    internal_cost_loss_formula: "NULL",
    product_linkage_requirement: "recommended",
    trid_edges_required: ["product_link"],
    source_confidence: { high: "reserved snapshot + linkage", medium: "snapshot only", low: "stale" },
    current_availability: "live_importer",
    blocked_reason: "Never auto-claim without ledger proof",
    implementation_priority: "P2",
  }),
  entry({
    family_key: "available_fba_discrepancy",
    display_name: "Available FBA discrepancy",
    classification: "review_signal_only",
    v1_reviewed: false,
    v2_status: "added_v2",
    required_reports_api: ["GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA", "GET_LEDGER_DETAIL_VIEW_DATA"],
    normalized_tables: ["amazon_manage_fba_inventory", "amazon_inventory_ledger"],
    registry_sync_kinds: ["MANAGE_FBA_INVENTORY", "INVENTORY_LEDGER"],
    required_identifiers: ["fnsku", "asin"],
    quantity_formula: "claim_quantity = NULL; display ABS(manage_fba - ledger_available)",
    fee_amount_formula: "NULL",
    estimated_amazon_payout_formula: "NULL",
    observed_reimbursement_formula: "N/A",
    internal_cost_loss_formula: "NULL",
    product_linkage_requirement: "recommended",
    trid_edges_required: ["product_link", "ledger_reference"],
    source_confidence: { high: "same-day manage_fba + ledger", medium: "manage_fba only", low: "stale >45d" },
    current_availability: "live_table",
    blocked_reason: "Promote only after ledger confirms loss",
    implementation_priority: "P2",
  }),
  entry({
    family_key: "stranded_inventory_signal",
    display_name: "Stranded inventory listing issue",
    classification: "review_signal_only",
    v1_reviewed: false,
    v2_status: "added_v2",
    required_reports_api: ["GET_STRANDED_INVENTORY_UI_DATA"],
    normalized_tables: ["planned: amazon_stranded_inventory"],
    registry_sync_kinds: [],
    required_identifiers: ["fnsku", "asin", "stranded_reason"],
    quantity_formula: "claim_quantity = NULL; display stranded_units",
    fee_amount_formula: "NULL",
    estimated_amazon_payout_formula: "NULL",
    observed_reimbursement_formula: "N/A",
    internal_cost_loss_formula: "NULL",
    product_linkage_requirement: "recommended",
    trid_edges_required: ["product_link", "listing_reference"],
    source_confidence: { high: "stranded report + linkage", medium: "report only", low: "no table" },
    current_availability: "planned_sp_api",
    blocked_reason: "amazon_stranded_inventory table not migrated",
    implementation_priority: "P2",
  }),
  entry({
    family_key: "expired_inventory_action_signal",
    display_name: "Expired/aged inventory action signal",
    classification: "review_signal_only",
    v1_reviewed: false,
    v2_status: "added_v2",
    required_reports_api: ["GET_FBA_INVENTORY_AGED_DATA", "GET_LEDGER_DETAIL_VIEW_DATA"],
    normalized_tables: ["amazon_inventory_ledger", "amazon_manage_fba_inventory"],
    registry_sync_kinds: ["INVENTORY_LEDGER", "MANAGE_FBA_INVENTORY"],
    required_identifiers: ["fnsku", "expiry_date", "inventory_age"],
    quantity_formula: "claim_quantity = NULL; display aged_units",
    fee_amount_formula: "NULL",
    estimated_amazon_payout_formula: "NULL",
    observed_reimbursement_formula: "N/A",
    internal_cost_loss_formula: "NULL",
    product_linkage_requirement: "recommended",
    trid_edges_required: ["product_link", "ledger_reference"],
    source_confidence: { high: "ledger expired event", medium: "manage_fba age hint", low: "no FEFO policy" },
    current_availability: "lifecycle_derived",
    blocked_reason: "May promote to disposed_without_reimbursement after ledger",
    implementation_priority: "P3",
  }),
  entry({
    family_key: "fba_overage_aged_inventory_fee_issue",
    display_name: "FBA overage / aged inventory fee",
    classification: "claim_family_when_source_available",
    v1_reviewed: false,
    v2_status: "added_v3",
    required_reports_api: ["GET_FBA_INVENTORY_AGED_DATA", "GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2"],
    normalized_tables: ["amazon_settlements", "amazon_manage_fba_inventory"],
    registry_sync_kinds: ["MANAGE_FBA_INVENTORY", "SETTLEMENT"],
    required_identifiers: ["fnsku", "inventory_age_bucket"],
    quantity_formula: "claim_quantity = 1 per overage fee line",
    fee_amount_formula: FEE_GAP,
    estimated_amazon_payout_formula: "N/A",
    observed_reimbursement_formula: "settlement overage/aged fee lines",
    internal_cost_loss_formula: "NULL",
    product_linkage_requirement: "required_before_trusted_money",
    trid_edges_required: ["product_link", "claim_to_settlement"],
    source_confidence: { high: "aged data + settlement fee", medium: "settlement only", low: "no aged ingest" },
    current_availability: "planned_sp_api",
    blocked_reason: "GET_FBA_INVENTORY_AGED_DATA not in registry",
    implementation_priority: "P2",
  }),
  entry({
    family_key: "recommended_removal_aged_inventory_action",
    display_name: "Recommended removal / aged inventory action",
    classification: "lifecycle_only",
    v1_reviewed: false,
    v2_status: "added_v3",
    required_reports_api: ["GET_RESTOCK_INVENTORY_RECOMMENDATIONS_REPORT", "GET_FBA_INVENTORY_AGED_DATA"],
    normalized_tables: ["amazon_manage_fba_inventory", "amazon_inventory_ledger"],
    registry_sync_kinds: ["MANAGE_FBA_INVENTORY"],
    required_identifiers: ["fnsku", "days_of_supply", "recommended_action"],
    quantity_formula: "claim_quantity = NULL; display recommended_removal_units",
    fee_amount_formula: "NULL",
    estimated_amazon_payout_formula: "NULL",
    observed_reimbursement_formula: "N/A",
    internal_cost_loss_formula: "NULL",
    product_linkage_requirement: "recommended",
    trid_edges_required: ["product_link"],
    source_confidence: { high: "restock rec + aged data", medium: "manage_fba only", low: "no report" },
    current_availability: "lifecycle_derived",
    blocked_reason: "Operational workflow — not auto-claim",
    implementation_priority: "P3",
  }),
  entry({
    family_key: "catalog_listing_fee_category_mismatch",
    display_name: "Catalog fee category mismatch",
    classification: "review_signal_only",
    v1_reviewed: false,
    v2_status: "added_v2",
    required_reports_api: ["Open Listings Report Lite", "GET_FBA_ESTIMATED_FBA_FEES_TXT_DATA", "Product Fees API"],
    normalized_tables: ["amazon_listing_report_rows_raw", "amazon_fee_preview"],
    registry_sync_kinds: ["ALL_LISTINGS", "FEE_PREVIEW"],
    required_identifiers: ["fnsku", "asin", "category", "browse_node"],
    quantity_formula: "claim_quantity = NULL; display category_dispute_count",
    fee_amount_formula: "display referral_fee_delta",
    estimated_amazon_payout_formula: "NULL at signal",
    observed_reimbursement_formula: "settlement referral lines",
    internal_cost_loss_formula: "NULL",
    product_linkage_requirement: "required_before_trusted_money",
    trid_edges_required: ["product_link", "listing_reference", "fee_preview_reference"],
    source_confidence: { high: "listings + fee_preview category", medium: "fee_preview only", low: "category map missing" },
    current_availability: "partial",
    blocked_reason: "Category-fee mapping incomplete",
    implementation_priority: "P3",
  }),
  entry({
    family_key: "stranded_expired_review_signal",
    display_name: "Stranded/expired umbrella (lifecycle grouping)",
    classification: "lifecycle_grouping_only",
    v1_reviewed: true,
    v2_status: "deprecated_grouping",
    required_reports_api: ["GET_RESTOCK_INVENTORY_RECOMMENDATIONS_REPORT", "GET_FBA_INVENTORY_AGED_DATA"],
    normalized_tables: ["amazon_manage_fba_inventory", "amazon_inventory_ledger"],
    registry_sync_kinds: ["MANAGE_FBA_INVENTORY"],
    required_identifiers: ["fnsku"],
    quantity_formula: "NULL — grouping only; use stranded_inventory_signal + expired_inventory_action_signal",
    fee_amount_formula: "NULL",
    estimated_amazon_payout_formula: "NULL",
    observed_reimbursement_formula: "N/A",
    internal_cost_loss_formula: "NULL",
    product_linkage_requirement: "recommended",
    trid_edges_required: ["product_link"],
    source_confidence: { high: "N/A", medium: "N/A", low: "deprecated for auto-claim" },
    current_availability: "lifecycle_derived",
    blocked_reason: "Superseded by split signals in V2/V3",
    implementation_priority: "deferred",
  }),
  entry({
    family_key: "orbit_fra_fight_list",
    display_name: "ORBIT/FRA fight list",
    classification: "claim_family",
    v1_reviewed: true,
    v2_status: "unchanged",
    required_reports_api: ["ORBIT 9-source XLSX bundle"],
    normalized_tables: ["claim_candidates (orbit_fra generator)", "amazon_reimbursements"],
    registry_sync_kinds: [],
    required_identifiers: ["fnsku", "asin", "sku", "orbit_row_key"],
    quantity_formula: "claim_quantity per ORBIT recovery row",
    fee_amount_formula: "recovery = qty × unit_cost (NOT sale price)",
    estimated_amazon_payout_formula: PAYOUT,
    observed_reimbursement_formula: OBSERVED,
    internal_cost_loss_formula: COGS_LOSS,
    product_linkage_requirement: "required_before_trusted_money",
    trid_edges_required: ["product_link", "orbit_source_row", "claim_to_reimbursement"],
    source_confidence: { high: "ORBIT row + COGS + anti-reimbursement", medium: "ORBIT row only", low: "unit_sale_price fallback active — remove" },
    current_availability: "live_generator",
    blocked_reason: "XLSX import apply blocked; COGS spine incomplete",
    implementation_priority: "P1",
  }),
];

/** Canonical V3 classification bucket counts (derived from CLAIM_FAMILY_MATRIX_V3). */
export const V3_CLASSIFICATION_COUNTS = {
  claim_family: CLAIM_FAMILY_MATRIX_V3.filter((e) => e.classification === "claim_family").length,
  claim_when_source_available: CLAIM_FAMILY_MATRIX_V3.filter(
    (e) => e.classification === "claim_family_when_source_available",
  ).length,
  review_signal_only: CLAIM_FAMILY_MATRIX_V3.filter((e) => e.classification === "review_signal_only").length,
  lifecycle_only: CLAIM_FAMILY_MATRIX_V3.filter(
    (e) => e.classification === "lifecycle_only" || e.classification === "lifecycle_grouping_only",
  ).length,
} as const;

export const V3_CLAIM_CAPABLE_COUNT =
  V3_CLASSIFICATION_COUNTS.claim_family + V3_CLASSIFICATION_COUNTS.claim_when_source_available;

export const CLAIM_VS_REVIEW_SIGNAL_DECISIONS_V3 = Object.fromEntries(
  CLAIM_FAMILY_MATRIX_V3.map((e) => [e.family_key, e.classification]),
);

export const QUANTITY_FORMULA_BY_FAMILY_V3 = Object.fromEntries(
  CLAIM_FAMILY_MATRIX_V3.map((e) => [e.family_key, e.quantity_formula]),
);

export const MONEY_FORMULA_BY_FAMILY_V3 = Object.fromEntries(
  CLAIM_FAMILY_MATRIX_V3.map((e) => [
    e.family_key,
    {
      fee_amount: e.fee_amount_formula,
      estimated_payout: e.estimated_amazon_payout_formula,
      observed_reimbursement: e.observed_reimbursement_formula,
      internal_cost_loss: e.internal_cost_loss_formula,
    },
  ]),
);

export const FEE_ADJUSTED_PAYOUT_RULE_BY_FAMILY_V3 = Object.fromEntries(
  CLAIM_FAMILY_MATRIX_V3.map((e) => [
    e.family_key,
    e.classification === "review_signal_only" || e.classification === "lifecycle_only" || e.classification === "lifecycle_grouping_only"
      ? "NULL — signal/lifecycle family; no trusted payout"
      : e.fee_amount_formula.includes("fee_overcharge") || e.fee_amount_formula.includes("storage_overcharge")
        ? "N/A — fee delta family; payout lane not primary"
        : FEE_ADJUSTED_REIMBURSEMENT_FORMULA.estimated_amazon_payout,
  ]),
);

export const IMPLEMENTATION_PRIORITY_V3 = [
  "P0: physical_return_scanner_issue, customer_return_not_reimbursed, removal_order_discrepancy, missing_reimbursement",
  "P1: partial_incorrect_reimbursement, settlement_refund_anomaly, fba_fee_overcharge, orbit_fra_fight_list, refund_without_return",
  "P2: fee report importers, ledger detail workers, inbound/placement/low-inventory, inventory signals UI, customer_shipment_sales_refund_mismatch",
  "P3: safet_followup, grade_resell, catalog_listing, finances_api_event_mismatch, recommended_removal_aged_inventory_action",
] as const;

export const FIRST_SAFE_5_FAMILIES_V3 = [
  "customer_return_not_reimbursed",
  "physical_return_scanner_issue",
  "removal_order_discrepancy",
  "missing_reimbursement",
  "partial_incorrect_reimbursement",
] as const;

export const SAFE_TO_IMPLEMENT_V3_CLAIM_READMODEL = "yes" as const;

export const NEXT_EXACT_PROMPT_V3 = `PHASE-CLAIM-FAMILY-ALGORITHM-MATRIX-V3-READMODEL-IMPLEMENT-V1

Mode: read-model API only — expose CLAIM_FAMILY_MATRIX_V3 (41 families) via GET /api/claims/center/algorithm-matrix-v3.

Include: official_report_type_mapping, missing_source_mapping, fee_adjusted_payout_rule_by_family, classification badges.

Do not write DB. Do not mutate claim_candidates. Do not implement generators.

Then PHASE-FEE-REPORT-IMPORTER-SCAFFOLD-V1 for registry gaps (low-inventory, returns-processing, inbound-placement, stranded).

Prerequisite workers: Ledger Detail View (1A), FBA Returns API (1B), Fee Preview API import.` as const;

/** Registry + crosswalk alignment audit helpers. */
export const REGISTRY_COVERAGE_AUDIT = {
  registry_sync_kind_count: Object.keys(AMAZON_REPORT_REGISTRY).length,
  crosswalk_live_count: AMAZON_REPORT_CROSSWALK_LIVE.length,
  crosswalk_placeholder_count: AMAZON_REPORT_CROSSWALK_PLACEHOLDERS.length,
  sp_api_mapped_count: Object.keys(SP_API_REPORT_TYPE_TO_SYNC_KIND).length,
  hard_rules: CLAIM_ALGORITHM_HARD_RULES,
};
